<%@ Page Language="C#" AutoEventWireup="true" CodeFile="ManagerList.aspx.cs" Inherits="ManagerList" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title>中国石油大学会议室管理系统</title>
    <style type="text/css">
        .style1
        {
        }
        .style2
        {
            width: 110px;
        }
        .style3
        {
            width: 137px;
        }
        .style4
        {
            width: 112px;
        }
    </style>
</head>
<body  background="IMAGES/bggg.jpg">
 <p align="center"><img src="IMAGES/logo.jpg" width="440" height="150"></p>
 <form id="form1" runat="server">
    <div>
    
        <table style="width:100%;">
            <tr>
                <td class="style4">
                    管理员列表</td>
                <td class="style2">&nbsp;
                    </td>
                <td class="style3">&nbsp;
                    </td>
                <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:LinkButton ID="LinkButton1" runat="server" onclick="LinkButton1_Click">退出登录</asp:LinkButton>
                    </td>
            </tr>
            <tr>
                <td class="style4">
                    查询条件：</td>
                <td class="style2">
                    管理员编号：</td>
                <td class="style3">
                    <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
                </td>
                <td>
                    <asp:Button ID="Button1" runat="server" Text="查询" onclick="Button1_Click" 
                        Width="85px" />
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:Button ID="huiyiliebiao" runat="server" Text="会议室列表"  onclick="Button4_Click"
                        Width="90px"
                       />
                </td>
            </tr>
            <tr>
                <td class="style4">&nbsp;
                    </td>
                <td class="style2">&nbsp;
                    </td>
                <td class="style3">&nbsp;
                    </td>
                <td>&nbsp;
                    </td>
            </tr>
            <tr>
                <td class="style1" colspan="4">
                    <asp:GridView ID="GridView1" runat="server" Width="100%" AllowPaging="True" 
                        AutoGenerateColumns="False" 
                        onpageindexchanging="GridView1_PageIndexChanging" PageSize="3" 
                        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                        <Columns>
                        <asp:BoundField DataField="managerid" HeaderText="管理员编号"><ItemStyle Width="20%" /></asp:BoundField>
                        <asp:BoundField DataField="managername" HeaderText="管理员姓名"><ItemStyle Width="20%" /></asp:BoundField>
                        <asp:BoundField DataField="telephone" HeaderText="管理员联系方式" ><ItemStyle Width="60%" /></asp:BoundField>
                        
                 </Columns>
                    </asp:GridView>
                </td>
            </tr>
        </table>
    
    </div>
    </form>
</body>
</html>
