<%@ Page Language="C#" AutoEventWireup="true" CodeFile="EquipListM.aspx.cs" Inherits="EquipListM" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>中国石油大学会议室管理系统_会议室列表</title>
    <style type="text/css">
        .style1
        {
        }
        .style2
        {
            width: 110px;
        }
        .style3
        {
            width: 137px;
        }
        .style4
        {
            width: 114px;
        }
        </style>
</head>
<body background="IMAGES/bggg.jpg">
 <p align="center"><img src="IMAGES/logo.jpg" width="440" height="150"></p>
 <form id="form1" runat="server">
    <div>
        <table style="width:100%;">
            <tr>
                <td class="style4">
                    设备列表</td><td><asp:Button ID="Buttoni" runat="server" Text="更新/新增设备" onclick="Buttoni_Click" 
                        Width="100px" /></td>
            </tr>
            <tr>
                <td class="style4">
                    查询条件：</td>
                <td>
                    设备名称：<asp:TextBox ID="TextBox1" runat="server"></asp:TextBox> 
                </td>         
            </tr>
            <tr><td class="style2"></td>
                 <td>
                    设备状态：<asp:TextBox ID="TextBox2" runat="server"></asp:TextBox> 
                     &nbsp;<asp:Button ID="status" runat="server" Text="查询" onclick="Button2_Click"
                     Width="105px" Height="21px" /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </td></tr>
           <tr><td class="style2"></td>
                 <td>
                    所在位置：<asp:TextBox ID="TextBox3" runat="server"></asp:TextBox> 
                </td></tr>
            <tr>
                <td class="style1" colspan="4">
                    <asp:GridView ID="GridView3" runat="server" Width="100%" AllowPaging="True" 
                        AutoGenerateColumns="False" 
                        onpageindexchanging="GridView3_PageIndexChanging" PageSize="4" 
                        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                        style="margin-right: 83px" 
                        onselectedindexchanged="GridView3_SelectedIndexChanged">
                        <Columns>
                        <asp:BoundField DataField="equipcode" HeaderText="设备编号"><ItemStyle Width="20%" /></asp:BoundField>
                        <asp:BoundField DataField="equipname" HeaderText="设备名称"><ItemStyle Width="30%" /></asp:BoundField>
                        <asp:BoundField DataField="location" HeaderText="所在位置" ><ItemStyle Width="30%" /></asp:BoundField>
                        <asp:BoundField DataField="status" HeaderText="设备状态" ><ItemStyle Width="20%" /></asp:BoundField>
                        
                 </Columns>
                    </asp:GridView>
                </td>
            </tr>
        </table>
    
    </div>
    </form>
</body>
</html>
