<%@ Page Language="C#" AutoEventWireup="true" CodeFile="huiyiList.aspx.cs" Inherits="huiyiList" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>中国石油大学会议室管理系统_会议室列表</title>
    <style type="text/css">
        .style1
        {
        }
        .style2
        {
            width: 110px;
        }
        .style3
        {
            width: 137px;
        }
        .style4
        {
            width: 114px;
        }
        </style>
</head>
<body background="IMAGES/bggg.jpg">
 <p align="center"><img src="IMAGES/logo.jpg" width="440" height="150"></p>
 <form id="form1" runat="server">
    <div>
    
        <table style="width:100%;">
            <tr>
                <td class="style4">
                    会议室列表</td>
                    <td><asp:Button ID="Button0" runat="server" Text="查看会议室设备" onclick="Button0_Click" 
                        Width="112px" /></td>
            </tr>
            <tr>
                <td class="style4">
                    查询条件：</td>
                <td class="style2">
                   会议室名：</td>
                <td class="style3">
                    <asp:TextBox ID="TB" runat="server"></asp:TextBox>
                </td>
                <td><asp:Button ID="chaxun" runat="server" Text="查询" onclick="Button3_Click" 
                        Width="92px" />   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:LinkButton ID="LinkButton1" runat="server" onclick="LinkButton1_Click">后退</asp:LinkButton>
                </td>
                <%--<td class="style2">
                   预约情况：
                    <asp:TextBox ID="TB2" runat="server"></asp:TextBox> 
                     &nbsp;<asp:Button ID="yuyue0" runat="server" Text="按预约情况查询" onclick="Button2_Click"
                     Width="105px" Height="21px" /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </td>--%></tr>
                <tr><td class="style2">
                </td><td class="style2">
                   预约情况：</td>
                <td class="style3">
                    <asp:TextBox ID="TB2" runat="server"></asp:TextBox>
                </td>
                <td><asp:Button ID="yuyue0" runat="server" Text="查询" onclick="Button2_Click" 
                        Width="92px" />   
                </td>
                </tr>
            <tr><td class="style1" colspan="4">
                    <asp:GridView ID="GridView2" runat="server" Width="100%" AllowPaging="True" 
                        AutoGenerateColumns="False" 
                        onpageindexchanging="GridView2_PageIndexChanging" PageSize="3" 
                        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                        style="margin-right: 83px" 
                        onselectedindexchanged="GridView2_SelectedIndexChanged">
                        <Columns>
                        <asp:BoundField DataField="huiyiid" HeaderText="会议室编号"><ItemStyle Width="20%" /></asp:BoundField>
                        <asp:BoundField DataField="huiyiname" HeaderText="会议室名"><ItemStyle Width="30%" /></asp:BoundField>
                        <asp:BoundField DataField="yuyue" HeaderText="预约情况" ><ItemStyle Width="30%" /></asp:BoundField> 
                 </Columns>
                    </asp:GridView>
                </td>
            </tr>
        </table>
    
    </div>
    <asp:Button ID="Button1" runat="server"  onclick="Button1_Click" Text="我要预约会议室"  
        Width="191px" />
    </form>
</body>
</html>
